Document: glf
Title: Debian glf Manual
Author: <insert document author here>
Abstract: This manual describes what glf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glf/glf.sgml.gz

Format: postscript
Files: /usr/share/doc/glf/glf.ps.gz

Format: text
Files: /usr/share/doc/glf/glf.text.gz

Format: HTML
Index: /usr/share/doc/glf/html/index.html
Files: /usr/share/doc/glf/html/*.html

  
